server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: generator-service
          uri: lb://generator-service
          predicates:
            - Path=/generator/**
          filters:
            - RewritePath=/generator/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

  application:
    name: gateway-servlice

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    ru.itis: DEBUG


jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

management:
  endpoints:
    web:
      exposure:
        include: '*'

