server:
  port: 9080

spring:
  application:
    name: generator-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


