spring:
  application:
    name: auth-service
#  cloud:
#    stream:
#      bindings:
#        userCreatedOutput-out-0:
#          destination: userCreatedOutput
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: root
    password: root
#    driver-class-name: org.postgresql.Driver
#    jpa:
#      properties:
#          hibernate:
#            dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#        ddl-auto: create


server:
  port: 8800

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400


